### ISSUE TITLE
Handle lists

### ISSUE THREAD

**Issue by Chlor87** [ren70n/goenvy#4]
Only json objects are handled at the moment. Handle lists as well please.

**Comment by Chlor87** [comment]
https://github.com/ren70n/goenvy/blob/4f08267fc59c018e74622fe0c0faf7a6891c5f75/goenvy.go#L46
I think this line will fail with array.

**Comment by ren70n** [comment]
Will be present in next version

**Comment by ren70n** [comment]
Solved by Chlor87 in 93c5176. Described in readme.md
